version: "3"

services:
  mysql-db:
    image: mysql/mysql-server:8.0
    tty: true
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'test_chat'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: '1234'
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - app-tier

  backend:
    build:
      context: ./backend
      args:
        DJANGO_ALLOWED_HOSTS: "*"
        DJANGO_SECRET_KEY: "*"
        DJANGO_CORS_ORIGIN_WHITELIST: "*"
    # command: python manage.py runserver 0.0.0.0:8000
    command: daphne -b 0.0.0.0 -p 8000 backend.asgi:application
    environment:
      DJANGO_SETTINGS_MODULE: backend.settings
    restart: always  
    # ports:
    #   - 8000:8000
    expose:
      - 8000
    volumes:
      - ./backend/:/backend/  
    tty: true
    networks:
      - app-tier

  frontend:
    build:
      context: ./front-react
    volumes:
      - ./front-react/:/front-react
      - build_folder:/front-react/build
      - ./front-react/node_modules/:/front-react/node_modules
    environment:
      -  WDS_SOCKET_PORT=3000
      - REACT_APP_BACKEND_URL= http://www.gilyeon.site
    tty: true
    networks:
      - app-tier

  nginx:
    build: ./nginx
    ports:
      - 80:8080
    volumes:
      - build_folder:/var/www/front-react
      - ./nginx/log:/var/log/nginx
    depends_on:
      - backend
      - frontend
    expose:
      - 80
    restart: always
    networks:
      - app-tier

volumes:
  mysql-data:
  build_folder:

networks:
  app-tier:
    driver: bridge