# Generated by Django 3.0 on 2023-07-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='user_id',
        ),
    ]
